name: Compile PaDEL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  PaDEL-Descriptor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: libPaDEL
      run: |
        cd libPaDEL
        ant
    - name: libPaDEL-Jobs
      run: |
        cd libPaDEL-Jobs
        ant
    - name: libPaDEL-Descriptor
      run: |
        cd libPaDEL-Descriptor
        ant
    - name: PaDEL-Descriptor
      run: |
        ant
